"""Entry point for running the InSEEDS model in coupled mode."""

from __future__ import annotations

import argparse
import sys

from pycopanlpjml.run import run_simulation

from inseeds.realisations.conservation_agriculture import Model


def run_inseeds(config_file: str) -> None:
    """Run the InSEEDS model with the given configuration file."""

    run_simulation(
        config_file=config_file,
        model_factory=Model,
        description="InSEEDS run",
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the InSEEDS model.")
    parser.add_argument(
        "config_file",
        help="Path to the LPJmL config JSON generated by pycoupler.",
    )
    run_inseeds(parser.parse_args().config_file)
    sys.exit(0)
